demo_app/urls.py
# type: ignore
from django.urls import path
from . import views
from .views import FoodDetail,CreateItem

app_name = 'demo_app'

urlpatterns = [
    path('',views.my_view),
    path('home/',views.food, name = 'food'),
    path('<int:pk>/',FoodDetail.as_view(),name = 'food_detail'),
    path('add/',CreateItem.as_view(),name = 'add_item'),
    path('update/<int:id>/',views.update_item,name = 'update_item'),
    path('delete/<int:id>/',views.delete_item,name = 'delete_item'),
]

demo_project/urls.py
# type: ignore
"""demo_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from wsgiref.simple_server import demo_app
from django.contrib import admin
from django.urls import include,path
from users import views as user_view
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo_app/',include('demo_app.urls')),
    path('register/',user_view.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_view.profile_page,name='profile')
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo_app/models.py
# type: ignore
from urllib import request
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class FoodList(models.Model):
    user_name = models.ForeignKey(User,on_delete = models.CASCADE,default = 1)
    item_name = models.CharField(max_length=100)
    item_desc = models.CharField(max_length=100)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://www.kindpng.com/picc/m/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png")

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('demo_app:food_detail',kwargs={'pk':self.pk})

    
    

users/models.py
# type: ignore
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

demo_app/forms.py
# type: ignore
from django import forms
from .models import FoodList

class AddItemForm(forms.ModelForm):
    class Meta:
        model = FoodList
        fields = '__all__'

users/forms.py
# type: ignore
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

demo_app/views.py
# type: ignore
from multiprocessing import context
from django.shortcuts import render,redirect
from django.http.response import HttpResponse
from django.views.generic import DetailView,CreateView

from .forms import AddItemForm
from .models import FoodList
# Create your views here.

def my_view(request):
    return HttpResponse("<b>this is my view</b>")

def food(request):
    item_list = FoodList.objects.all()
    context = {
        'item_list' : item_list,
    }
    return render(request,'demo_app/food.html',context)

def food_detail(request,item_id):
    item = FoodList.objects.get(pk=item_id)
    context = {
        'item' : item,
    }
    return render(request,'demo_app/food_detail.html',context)

class FoodDetail(DetailView):
    model = FoodList
    template_name = 'demo_app/food_detail.html'
    context_object_name = 'item'
    

def add_item(request):
    form = AddItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('demo_app:food')
    return render(request,'demo_app/add-item.html',{'form':form })

class CreateItem(CreateView):
    model = FoodList
    fields = ['item_name','item_price','item_image','item_desc']
    template_name = 'demo_app/add-item.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request,id):
    item = FoodList.objects.get(id = id)
    form = AddItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('demo_app:food')
    return render(request,'demo_app/add-item.html',{'form':form,'item':item})

def delete_item(request,id):
    item = FoodList.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('demo_app:food')
    return render(request,'demo_app/delete-item.html',{'item':item})

users/views.py
# type: ignore
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . forms import RegisterForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account has been created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/sign-up.html',{'form': form})

@login_required
def profile_page(request):
    return render(request,'users/profile.html')

demo_app/templates/demo_app/add-item.html
{% extends 'demo_app/base.html' %}
{% block body %}
<!-- <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form> -->


<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <form action="" method="POST"></form>
                <div class="mb-3 text-center">
                    <label class="form-label bg-warning">ADD Items</label>
                    {% csrf_token %}
                    {% for field in form %}

                    <div class="mb-3 text-center">
                        {{field.name}}<br>
                        {{field}}
                    </div>

                    {% endfor %}
                    <button type="submit" class="btn btn-primary">ADD</button>
                </div>

                </form>
            </div>
        </div>

    </div>
</div>
{% endblock %}

demo_app/templates/demo_app/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <title>Spice Restaurant</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">About us</a>
                    </li>
                </ul>
            </div>
            <ul class="nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'demo_app:add_item' %}">Add Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">View Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Delete Item</a>
                </li>

            </ul>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>

    </nav>
    {% if messages %}
    {% for msg in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{msg}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>

</html>

demo_app/templates/demo_app/delete-item.html
<form method="POST">
    {% csrf_token %}
    <h2>Are You Sure Want TO Delete {{item.item_name}}</h2>
    <button type="submit">OK</button>
</form>

demo_app/templates/demo_app/food.html
{% extends 'demo_app/base.html' %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
</head>

<body>
    {% block body %}
    {% for jelly in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card" width="250" src="{{ jelly.item_image }}"/>
        </div>
        <div class="col-md-4">
            <h2>{{ jelly.item_name }}</h2>
            <h4>Rs {{ jelly.item_price }}</h4>
        </div>
        <div class="col-md-2">
            <a href="{% url 'demo_app:update_item' jelly.id %}" class="btn btn-info">Update</a>
            <a href="{% url 'demo_app:delete_item' jelly.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'demo_app:food_detail' jelly.id %}" class="btn btn-primary">Details</a>
        </div>
    </div>
    {% endfor %}
    {% endblock %}




    


    <!-- <ul>
        <li>

            <a href="{% url 'demo_app:food_detail' jelly.id %}">{{ jelly.id }} {{ jelly.item_name }}</a>
        </li>
    </ul> -->

    
</body>

</html>

demo_app/templates/demo_app/food_detail.html
{% extends 'demo_app/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mt-2">
            <img src="{{ item.item_image }}" class="card" width="500" alt="">
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2>Description :- </h2>
            <p style="margin-left: 50px">{{ item.item_desc }}</p>
            <h3>Price = {{ item.item_price }} Rs</h3>
        </div>
    </div>
</div>







{% endblock %}

users/templates/users/login.html
{% extends 'demo_app/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <form action="" method="POST"></form>
                <div class="mb-3 text-center">
                    <label class="form-label bg-warning">Log In</label>
                    {% csrf_token %}
                    {% for field in form %}

                    <div class="mb-3 text-center">
                        {{field.name}}
                        {{field}}
                    </div>

                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>

                </form>
            </div>
        </div>

    </div>
</div>




{% endblock %}

users/templates/users/logout.html
<h2>You have been Logged out successfully</h2>

users/templates/users/profile.html
<img src="{{user.profile.image.url}}" width="100px" alt="">
<h2>{{ user.username }}</h2>

users/templates/users/sign-up.html
{% extends 'demo_app/base.html' %}

{% block body %}
<!-- <form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input class="btn" type="submit">
</form> -->


<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <form action="" method="POST"></form>
                <div class="mb-3 text-center">
                    <label class="form-label bg-warning">Register</label>
                    {% csrf_token %}
                    {% for field in form %}

                    <div class="mb-3 text-center">
                        {{field.name}}<br>
                        {{field}}
                    </div>

                    {% endfor %}
                    <button type="submit" class="btn btn-primary">SignUp</button>
                </div>

                </form>
            </div>
        </div>

    </div>
</div>
{% endblock %}